### ISSUE TITLE
db4bix:TimerProcessor: Cannot read property 'data'

### ISSUE THREAD

**Issue by 74andreyg** [vagabondan/node-db4bix#10]
Hello
Help me please ...
After db4bix starting I got error
[2020/01/15 - 15:01:34] db4bix:Configurator:debug getConfigsFromZabbix started +30s
[2020/01/15 - 15:01:34] db4bix:TimerProcessor:error Error on updatePeriodically: Cannot read property 'data' of undefined TypeError: Cannot read property 'data' of undefined
    at Configurator.updateConfiguration (/opt/node-db4bix/libs/configurator/index.js:293:35)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async TimerProcessor.updatePeriodically (/opt/node-db4bix/libs/timerProcessor/index.js:307:20)
    at async Timeout.setQuery [as _onTimeout] (/opt/node-db4bix/libs/timerProcessor/index.js:248:25) +30s

What is a problem? Zabbix server version is 4.4.1 and version in db4bix.config is the same

**Comment by vagabondan** [comment]
Hi! It seems that you have no configuration items at Zabbix Server.
Please check the correctness of configuration item key (configSuffix).
I'll modify the message for more logically understandable in future versions.

**Comment by 74andreyg** [comment]
You are right !!! Thanks a lot
