### ISSUE TITLE
Error starting db4bix

### ISSUE THREAD

**Issue by ResponsableSeguridadAudifilm** [vagabondan/node-db4bix#11]
Hello, I installed last Zabbix version on a Ubuntu 18.04 server.
I tried node-db4fix, but it gives me an error when trying to execute it.
Versions of node are:
npm -v
3.5.2
node -v
v12.16.1
(I also tried with node version v8.16.2)

When I run it I get:
root@ubuntu-Zabbix:/opt/node-db4bix# DEBUG='*' node index.js
[2020/04/06 - 03:54:10] db4bix:ZabbixSender:debug Init +0ms
[2020/04/06 - 03:54:17] db4bix:Configurator:debug Init +0ms
[2020/04/06 - 03:54:17] db4bix:DBs:debug Init +0ms
[2020/04/06 - 03:55:21] db4bix:MSSQL:debug Init +0ms
[2020/04/06 - 03:55:21] db4bix:MYSQL:debug Init +0ms
[2020/04/06 - 03:55:21] db4bix:ORACLE:debug Init +0ms
[2020/04/06 - 03:55:26] db4bix:PostgreSQL:debug Init +0ms
/opt/node-db4bix/node_modules/bindings/bindings.js:135
  throw err;
  ^
Error: Could not locate the bindings file. Tried:
 → /opt/node-db4bix/build/db4bix_preproc.node
 → /opt/node-db4bix/build/Debug/db4bix_preproc.node
 → /opt/node-db4bix/build/Release/db4bix_preproc.node
 → /opt/node-db4bix/out/Debug/db4bix_preproc.node
 → /opt/node-db4bix/Debug/db4bix_preproc.node
 → /opt/node-db4bix/out/Release/db4bix_preproc.node
 → /opt/node-db4bix/Release/db4bix_preproc.node
 → /opt/node-db4bix/build/default/db4bix_preproc.node
 → /opt/node-db4bix/compiled/8.16.2/linux/x64/db4bix_preproc.node
 → /opt/node-db4bix/addon-build/release/install-root/db4bix_preproc.node
 → /opt/node-db4bix/addon-build/debug/install-root/db4bix_preproc.node
 → /opt/node-db4bix/addon-build/default/install-root/db4bix_preproc.node
 → /opt/node-db4bix/lib/binding/node-v57-linux-x64/db4bix_preproc.node
    at bindings (/opt/node-db4bix/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/opt/node-db4bix/libs/zabbixPreprocessor/index.js:2:33)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/node-db4bix/libs/timerProcessor/index.js:9:28)

What could be the problem?

I attach full install instructions I used.
Best regards!

[setup.txt](https://github.com/vagabondan/node-db4bix/files/4435552/setup.txt)

**Comment by oitss1** [comment]
The similar problem was resolved by installing pcre-devel-8.32-17.el7.x86_64 packet in RHEL 7.

**Comment by ResponsableSeguridadAudifilm** [comment]
As I see server is using Perl5 (v5.26.1) I installed libpcre3-dev:

https://packages.ubuntu.com/search?suite=default&section=all&arch=any&keywords=libpcre&searchon=names

Package libpcre3-dev
bionic (18.04LTS) (libdevel): Old Perl 5 Compatible Regular Expression Library - development files
2:8.39-9: amd64 arm64 armhf i386 ppc64el s390x

apt-get install libpcre3-dev
...

But same error...
